name: mc_locale_keys_class_generator
description: A sample command-line application with basic argument parsing.
version: 0.0.2
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  args: ^2.6.0
  recase: ^4.1.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8
